export const NAVIGATION = {
  HOME: '/',
  SETTINGS: '/settings',
  MODULATION: '/modulation',
  AUTO_TUNE: '/modulation/auto-tune',
  AMPLIFIER: '/modulation/amplifier',
  BIT_CRUSHER: '/modulation/bit-crusher',
  CHORUS: '/modulation/chorus',
  DISTORTION: '/modulation/distortion',
  PICH_SHIFTER: '/modulation/pitch-shifter',
  REVERB: '/modulation/reverb',
  VIBRATO: '/modulation/vibrato',
  VOCODER: '/modulation/vocoder',
  RECORDER: '/recorder',
}