/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecorderRouteImport } from './routes/recorder'
import { Route as ModulationRouteImport } from './routes/modulation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulationVocoderRouteImport } from './routes/modulation/vocoder'
import { Route as ModulationVibratoRouteImport } from './routes/modulation/vibrato'
import { Route as ModulationReverbRouteImport } from './routes/modulation/reverb'
import { Route as ModulationPitchShifterRouteImport } from './routes/modulation/pitch-shifter'
import { Route as ModulationDistortionRouteImport } from './routes/modulation/distortion'
import { Route as ModulationChorusRouteImport } from './routes/modulation/chorus'
import { Route as ModulationBitCrusherRouteImport } from './routes/modulation/bit-crusher'
import { Route as ModulationAutoTuneRouteImport } from './routes/modulation/auto-tune'
import { Route as ModulationAmplifierRouteImport } from './routes/modulation/amplifier'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorderRoute = RecorderRouteImport.update({
  id: '/recorder',
  path: '/recorder',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulationRoute = ModulationRouteImport.update({
  id: '/modulation',
  path: '/modulation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulationVocoderRoute = ModulationVocoderRouteImport.update({
  id: '/vocoder',
  path: '/vocoder',
  getParentRoute: () => ModulationRoute,
} as any)
const ModulationVibratoRoute = ModulationVibratoRouteImport.update({
  id: '/vibrato',
  path: '/vibrato',
  getParentRoute: () => ModulationRoute,
} as any)
const ModulationReverbRoute = ModulationReverbRouteImport.update({
  id: '/reverb',
  path: '/reverb',
  getParentRoute: () => ModulationRoute,
} as any)
const ModulationPitchShifterRoute = ModulationPitchShifterRouteImport.update({
  id: '/pitch-shifter',
  path: '/pitch-shifter',
  getParentRoute: () => ModulationRoute,
} as any)
const ModulationDistortionRoute = ModulationDistortionRouteImport.update({
  id: '/distortion',
  path: '/distortion',
  getParentRoute: () => ModulationRoute,
} as any)
const ModulationChorusRoute = ModulationChorusRouteImport.update({
  id: '/chorus',
  path: '/chorus',
  getParentRoute: () => ModulationRoute,
} as any)
const ModulationBitCrusherRoute = ModulationBitCrusherRouteImport.update({
  id: '/bit-crusher',
  path: '/bit-crusher',
  getParentRoute: () => ModulationRoute,
} as any)
const ModulationAutoTuneRoute = ModulationAutoTuneRouteImport.update({
  id: '/auto-tune',
  path: '/auto-tune',
  getParentRoute: () => ModulationRoute,
} as any)
const ModulationAmplifierRoute = ModulationAmplifierRouteImport.update({
  id: '/amplifier',
  path: '/amplifier',
  getParentRoute: () => ModulationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modulation': typeof ModulationRouteWithChildren
  '/recorder': typeof RecorderRoute
  '/settings': typeof SettingsRoute
  '/modulation/amplifier': typeof ModulationAmplifierRoute
  '/modulation/auto-tune': typeof ModulationAutoTuneRoute
  '/modulation/bit-crusher': typeof ModulationBitCrusherRoute
  '/modulation/chorus': typeof ModulationChorusRoute
  '/modulation/distortion': typeof ModulationDistortionRoute
  '/modulation/pitch-shifter': typeof ModulationPitchShifterRoute
  '/modulation/reverb': typeof ModulationReverbRoute
  '/modulation/vibrato': typeof ModulationVibratoRoute
  '/modulation/vocoder': typeof ModulationVocoderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modulation': typeof ModulationRouteWithChildren
  '/recorder': typeof RecorderRoute
  '/settings': typeof SettingsRoute
  '/modulation/amplifier': typeof ModulationAmplifierRoute
  '/modulation/auto-tune': typeof ModulationAutoTuneRoute
  '/modulation/bit-crusher': typeof ModulationBitCrusherRoute
  '/modulation/chorus': typeof ModulationChorusRoute
  '/modulation/distortion': typeof ModulationDistortionRoute
  '/modulation/pitch-shifter': typeof ModulationPitchShifterRoute
  '/modulation/reverb': typeof ModulationReverbRoute
  '/modulation/vibrato': typeof ModulationVibratoRoute
  '/modulation/vocoder': typeof ModulationVocoderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modulation': typeof ModulationRouteWithChildren
  '/recorder': typeof RecorderRoute
  '/settings': typeof SettingsRoute
  '/modulation/amplifier': typeof ModulationAmplifierRoute
  '/modulation/auto-tune': typeof ModulationAutoTuneRoute
  '/modulation/bit-crusher': typeof ModulationBitCrusherRoute
  '/modulation/chorus': typeof ModulationChorusRoute
  '/modulation/distortion': typeof ModulationDistortionRoute
  '/modulation/pitch-shifter': typeof ModulationPitchShifterRoute
  '/modulation/reverb': typeof ModulationReverbRoute
  '/modulation/vibrato': typeof ModulationVibratoRoute
  '/modulation/vocoder': typeof ModulationVocoderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modulation'
    | '/recorder'
    | '/settings'
    | '/modulation/amplifier'
    | '/modulation/auto-tune'
    | '/modulation/bit-crusher'
    | '/modulation/chorus'
    | '/modulation/distortion'
    | '/modulation/pitch-shifter'
    | '/modulation/reverb'
    | '/modulation/vibrato'
    | '/modulation/vocoder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/modulation'
    | '/recorder'
    | '/settings'
    | '/modulation/amplifier'
    | '/modulation/auto-tune'
    | '/modulation/bit-crusher'
    | '/modulation/chorus'
    | '/modulation/distortion'
    | '/modulation/pitch-shifter'
    | '/modulation/reverb'
    | '/modulation/vibrato'
    | '/modulation/vocoder'
  id:
    | '__root__'
    | '/'
    | '/modulation'
    | '/recorder'
    | '/settings'
    | '/modulation/amplifier'
    | '/modulation/auto-tune'
    | '/modulation/bit-crusher'
    | '/modulation/chorus'
    | '/modulation/distortion'
    | '/modulation/pitch-shifter'
    | '/modulation/reverb'
    | '/modulation/vibrato'
    | '/modulation/vocoder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulationRoute: typeof ModulationRouteWithChildren
  RecorderRoute: typeof RecorderRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorder': {
      id: '/recorder'
      path: '/recorder'
      fullPath: '/recorder'
      preLoaderRoute: typeof RecorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulation': {
      id: '/modulation'
      path: '/modulation'
      fullPath: '/modulation'
      preLoaderRoute: typeof ModulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulation/vocoder': {
      id: '/modulation/vocoder'
      path: '/vocoder'
      fullPath: '/modulation/vocoder'
      preLoaderRoute: typeof ModulationVocoderRouteImport
      parentRoute: typeof ModulationRoute
    }
    '/modulation/vibrato': {
      id: '/modulation/vibrato'
      path: '/vibrato'
      fullPath: '/modulation/vibrato'
      preLoaderRoute: typeof ModulationVibratoRouteImport
      parentRoute: typeof ModulationRoute
    }
    '/modulation/reverb': {
      id: '/modulation/reverb'
      path: '/reverb'
      fullPath: '/modulation/reverb'
      preLoaderRoute: typeof ModulationReverbRouteImport
      parentRoute: typeof ModulationRoute
    }
    '/modulation/pitch-shifter': {
      id: '/modulation/pitch-shifter'
      path: '/pitch-shifter'
      fullPath: '/modulation/pitch-shifter'
      preLoaderRoute: typeof ModulationPitchShifterRouteImport
      parentRoute: typeof ModulationRoute
    }
    '/modulation/distortion': {
      id: '/modulation/distortion'
      path: '/distortion'
      fullPath: '/modulation/distortion'
      preLoaderRoute: typeof ModulationDistortionRouteImport
      parentRoute: typeof ModulationRoute
    }
    '/modulation/chorus': {
      id: '/modulation/chorus'
      path: '/chorus'
      fullPath: '/modulation/chorus'
      preLoaderRoute: typeof ModulationChorusRouteImport
      parentRoute: typeof ModulationRoute
    }
    '/modulation/bit-crusher': {
      id: '/modulation/bit-crusher'
      path: '/bit-crusher'
      fullPath: '/modulation/bit-crusher'
      preLoaderRoute: typeof ModulationBitCrusherRouteImport
      parentRoute: typeof ModulationRoute
    }
    '/modulation/auto-tune': {
      id: '/modulation/auto-tune'
      path: '/auto-tune'
      fullPath: '/modulation/auto-tune'
      preLoaderRoute: typeof ModulationAutoTuneRouteImport
      parentRoute: typeof ModulationRoute
    }
    '/modulation/amplifier': {
      id: '/modulation/amplifier'
      path: '/amplifier'
      fullPath: '/modulation/amplifier'
      preLoaderRoute: typeof ModulationAmplifierRouteImport
      parentRoute: typeof ModulationRoute
    }
  }
}

interface ModulationRouteChildren {
  ModulationAmplifierRoute: typeof ModulationAmplifierRoute
  ModulationAutoTuneRoute: typeof ModulationAutoTuneRoute
  ModulationBitCrusherRoute: typeof ModulationBitCrusherRoute
  ModulationChorusRoute: typeof ModulationChorusRoute
  ModulationDistortionRoute: typeof ModulationDistortionRoute
  ModulationPitchShifterRoute: typeof ModulationPitchShifterRoute
  ModulationReverbRoute: typeof ModulationReverbRoute
  ModulationVibratoRoute: typeof ModulationVibratoRoute
  ModulationVocoderRoute: typeof ModulationVocoderRoute
}

const ModulationRouteChildren: ModulationRouteChildren = {
  ModulationAmplifierRoute: ModulationAmplifierRoute,
  ModulationAutoTuneRoute: ModulationAutoTuneRoute,
  ModulationBitCrusherRoute: ModulationBitCrusherRoute,
  ModulationChorusRoute: ModulationChorusRoute,
  ModulationDistortionRoute: ModulationDistortionRoute,
  ModulationPitchShifterRoute: ModulationPitchShifterRoute,
  ModulationReverbRoute: ModulationReverbRoute,
  ModulationVibratoRoute: ModulationVibratoRoute,
  ModulationVocoderRoute: ModulationVocoderRoute,
}

const ModulationRouteWithChildren = ModulationRoute._addFileChildren(
  ModulationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulationRoute: ModulationRouteWithChildren,
  RecorderRoute: RecorderRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
